apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: {{ .Values.namespace.name }} 
spec:
  selector:
    app: techtrends
  ports:
    - name: http
      protocol: TCP
      port: 4111
      targetPort: 3111
  type: ClusterIP
