namespace:
  name: prod

service:
  port: 7111
  type: ClusterIP

image:
  repository: 0644012368/techtrends
  tag: latest
  pullPolicy: Always

replicaCount: 5

resources:
  requests:
    memory: 128Mi
    cpu: 350m
  limits:
    memory: 256Mi
    cpu: 500m
