name: TechTrends - Package with Docker

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          python-version: [3.7, 3.8]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: "0644012368"
          password: "0644012368"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./project/techtrends
          file: ./project/techtrends/Dockerfile # Path to your Dockerfile
          push: true
          tags: techtrends:latest
